/**
 * Municipios del área de influencia UTEN (`municipio_podas`).
 * Misma lista que formularios móviles y el seed API — fija en código para Digitar.
 */

export const MUNICIPIO_PODAS_OPTIONS = [
  { key: "BuenosAires", value: "BuenosAires" },
  { key: "Caloto", value: "Caloto" },
  { key: "Corinto", value: "Corinto" },
  { key: "Guachene", value: "Guachene" },
  { key: "Miranda", value: "Miranda" },
  { key: "Padilla", value: "Padilla" },
  { key: "PuertoTejada", value: "PuertoTejada" },
  { key: "SantanderdeQuilichao", value: "SantanderdeQuilichao" },
  { key: "Suarez", value: "Suarez" },
  { key: "VillaRica", value: "VillaRica" },
  { key: "Cajibio", value: "Cajibio" },
  { key: "ElTambo", value: "ElTambo" },
  { key: "LaSierra", value: "LaSierra" },
  { key: "Morales", value: "Morales" },
  { key: "Piendamo", value: "Piendamo" },
  { key: "Popayan", value: "Popayan" },
  { key: "Rosas", value: "Rosas" },
  { key: "Paispamba", value: "Paispamba" },
  { key: "Timbio", value: "Timbio" },
  { key: "Almaguer", value: "Almaguer" },
  { key: "Argelia", value: "Argelia" },
  { key: "Balboa", value: "Balboa" },
  { key: "Bolivar", value: "Bolivar" },
  { key: "Florencia", value: "Florencia" },
  { key: "LaVega", value: "LaVega" },
  { key: "Mercaderes", value: "Mercaderes" },
  { key: "PatiaElBordo", value: "PatiaElBordo" },
  { key: "Piamonte", value: "Piamonte" },
  { key: "SanSebastian", value: "SanSebastian" },
  { key: "SantaRosa", value: "SantaRosa" },
  { key: "Sucre", value: "Sucre" },
  { key: "Guapi", value: "Guapi" },
  { key: "LopezdeMicay", value: "LopezdeMicay" },
  { key: "Timbiqui", value: "Timbiqui" },
  { key: "Caldono", value: "Caldono" },
  { key: "Inza", value: "Inza" },
  { key: "Jambalo", value: "Jambalo" },
  { key: "Belalcazar", value: "Belalcazar" },
  { key: "Coconuco", value: "Coconuco" },
  { key: "Silvia", value: "Silvia" },
  { key: "Toribio", value: "Toribio" },
  { key: "Totoro", value: "Totoro" },
  { key: "other", value: "Otro municipio" },
] as const;
